### ISSUE TITLE
maintain R 2.15.0 support (for managed environments)

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1641]
Single issue to group changes in the code which breaks stated dependency on R 2.15.0.

- [x] `R_xlen_t` symbol in `fwrite`
- [x] `anyNA` in `all.equal.data.table`
- [x] `setNames(nm=cols)` in `split.data.table`
- [x] `setNames(nm=sugg_pkgs)` in `tests.Rraw`
- [x] `[<-.data.table` in `transform.data.table` - `transform(.SD)` example in `transform.data.table.Rd`
- [x] R 2.15.0 crashes on `as.factor(NA)` / `factor(NA)`, some tests needs to be altered (4 tests in 1639.x)
- [x] `split.data.frame` crashes when split by NA factors or `NA_character_`, another tests in 1639.x
- [x] non-equi join tests in `tests.Rraw`, `mget` needed environment argument, solved in d41adf1caab24d60cbf9da4938ddcf088a1188ba
- [x] `Comparing ‘knitr.Rout’ to ‘knitr.Rout.save’ ...10d9` - `requireNamespace(quietly=T)` didn't suppress pkg loading message in 2.15
- [x] 2 tests failed: 1613.33, 1613.36 - related to `all.equal.list` which previously didn't output `dQuote("a name")` as component name but just integer
- [x] test 1617 failed - related to #1281 - change in R 3.1
- [ ] another 2 tests 1619.1, 1619.2 related to re-open issue #1270 - tests suppresses (in d41adf1caab24d60cbf9da4938ddcf088a1188ba) till it fixed
- [x] test `1661.1` #1015 fails without giving test number due to R < 3.1 warning
- [x] ~~`as.factor(NA)` can be handled on 2.15.0 with `as.factor(character())[1L]`~~ update: nope, would crash anyway in lower level operations on NA factor

----

### Reproducibility:

Just plain R issue
```
docker run -it jangorecki/r-2.15.0
as.factor(NA)
```

with installation of latest data.table:
```
docker run -it --net=host jangorecki/r-2.15.0
download.packages("data.table", destdir = ".", repos = "http://Rdatatable.github.io/data.table", type = "source")
install.packages("data.table_1.9.7.tar.gz", repos=NULL, type="source")
```

Optionally to bash
```
docker run -it --net=host jangorecki/r-2.15.0 /bin/bash
curl -O https://Rdatatable.github.io/data.table/src/contrib/data.table_1.9.7.tar.gz
export _R_CHECK_FORCE_SUGGESTS_=FALSE
R2 CMD check data.table_1.9.7.tar.gz --no-manual --as-cran
```
When using from bash remember to use `R2` instead of `R`.
