### ISSUE TITLE
Master task for fread bugs / proposals

### ISSUE THREAD

**Issue by st-pasha** [Rdatatable/data.table#2247]
## Bugs (critical)
- [x] Occasionally fread garbles the input data (#2260)
- [x] Crash when fread underestimates number of rows in a file (#2246)
- [x] Crash when `nrows` argument is too small relative to the size of the file (#2243)
- [x] Crash when reading a file whose size is a multiple of 4096 (#2194, #2228, #2238, #1464)
- [x] Crash when using parameter `skip` with files whose size is a multiple of 4096 (#2201)
- [x] Potential crash when error happens on a line containing `%` character (#2287)
- [x] Crash on Windows when seeing less columns than expected, and `fill` is false (#2299)
- [x] Possible crash when a line has extra sep at the end (#2523)

## Bugs (core)
- [x] unable to handle mis-quoted fields if they first appear after the first 100 lines (#2265)
- [x] big integers are read incorrectly (#2250, #1618)
- [x] when one of `na.strings` is a number, it may fail to work properly (#2222)
- [x] eliminate message "can be slowed down by other apps" (#2197)
- [x] wrong heuristic in predicting num cols: quote rule should take precedence (#2196)
- [x] fread may report negative waiting time in verbose mode (#2175)
- [x] fread may produce error "sampling jump point is before the last jump ended" (#2173)
- [x] fread may produce error "could not find first good line start after jump point 1" (#2134)
- [x] fread may fail to "find first good line start" even with `fill=True` (#2267)
- [x] better handle  NAs in single-column input (#2106)
- [x] fread reports warning about "found last consistent line but text exists afterwards" even when `nrows` argument is used (#1671)
- [x] fread discards column names if there are less names than data columns (#1625)
- [x] fread cannot read a file if it ends with 0x1A character (#1612)
- [x] if incomplete row occurs at the top of the file, fread skips it rather than suggesting to use "fill=TRUE" (#1416)
- [x] type detector should take into account parameters `skip` and `nrows` (#1267)
- [x] no longer reads all files from the extended test suite (#2285)
- [x] unable to parse a file if it contains very long multiline text fields (#2395, #2600)
- [x] fread's `select` should advise using `drop` if receiving negative indices (#2423)
- [ ] Cannot parse file containing embedded `NUL`s (#2435, #2496)
- [x] unable to read file containing quoted last field, which is excluded via `select` (#2464)
- [ ] `strip.white=FALSE` is not respected (#2492)
- [x] NA values are accidentally omitted in a 1-column file (#2515)
- [x] 1x1 DT with NA value is read should be read as logical, not character (#2516)
- [x] Number of rows is estimated incorrectly for small files (#2518)
- [x] File with quoted integer fields may be read as character (#2520)
- [x] fread fails if maxnrow=0 and file has just 1 header row (#2512)
- [x] erroneous detection of column names when they are not present (#2526)
- [x] `\r` newlines are squashed in a single-column file (#2542)
- [x] last line with whitespace messes up sep detection for small files (#2543)
- [x] Error "jump X did not finish counting rows exactly where jump X+1 found its first good line start" (#2561)
- [ ] quoted na strings are not recognized properly (#2586)
- [x] error when int columns becomes string containing sep on an out-of-sample row (#2614)
- [x] some strings are erroneously parsed as floats (#2625)
- [x] explicitly specified `sep` may sometimes be ignored (#2666)
- [ ] fread may improperly detect sep within quoted fields (#2667)
- [x] NAs may not be recognized correctly if surrounded by whitespace (#2697)
- [x] logical01 parameter may prevent column name detection (#2735)
- [x] quote rule may be detected wrongly for a 1-column file (#2744)
- [x] sep is not detected when nrows=0 (#2747)
- [x] dec=',' may cause file to be parsed incorrectly (#2750)
- [x] na.strings="0" is not permitted (#2927)
- [ ] self-healing regression for fill=TRUE with unmatched quotes (#2859)

## Bugs (R)
- [x] Memory leak on Windows when reading file with many subnormal floats (#918)
- [ ] escaped / doubled quote marks should be unescaped / undoubled (#1109, #1299)
- [x] add option to customize location where temporary files are stored (#1139)
- [x] using `select = NULL` causes an error (#2007)
- [x] Crash when using fread in conjunction with xlsx package (#2220)
- [x] colClasses=integer no longer working (#2251)
- [x] fread wastes too much time to match URL regexp when input is an in-memory buffer (#2531)
- [ ] `integer64` parameter does not work out-of-sample (#2749, #2607)
- [x] `colClasses="logical"` may produce a spurious error (#2766)
- [ ] fread session is not cleaned up after a try-catch statement (#2904)

## Feature requests (core)
- [x] support hexadecimal floating point numbers (#2316)
- [ ] refactor code so that file reading is done through a single common procedure (#2261)
- [x] better report file size in verbose mode (#2252)
- [x] `fread` should distinguish between empty string and n/a string (#2281, #2217, #2214, #1159)
- [ ] add ability to skip "broken" lines and report them to the user in the end (#2163, #2263, #2765)
- [ ] auto-detect NA strings in a column (#2100)
- [ ] add option to skip initial rows but not the header (#2080)
- [ ] allow multi-character field separators (#2011 )
- [x] detect newlines more reliably if file contains different newlines (#2248, #1183)
- [x] allow fread to understand files where first column contains row indices and have no name (for example such file may be produced by `write.table`) (#1818, #763)
- [ ] make fread able to process files with irregular number of columns, where some rows may have more columns than originally anticipated (#1812)
- [x] fread should understand special float values `1#.INF`, `1.#IND`, `1.#QNAN`, and `1.#SNAN` (#1800)
-  ~~allow fread to process input file in chunks, i.e. add ability to stop/resume scanning (#1721)~~
- [x] support for CSVY format (#1701)
- [ ] allow `nrow` argument to be negative, meaning skip that many lines from the end (#1643)
- [ ] add support for numbers with thousand separator (#1636, #1723)
- [x] add simple option to read file without splitting it into fields (#1616, #1627, #1518)
- [ ] fread should be able to understand fixed-width format files (#1345)
- [x] when detecting columns the case of single column should also be considered (#1073)
- [x] make warning messages less intimidating (#1042)
- ~~allow reading part of a file >4Gb on a 32-bit machine (#949)~~
- [ ] add option to skip lines starting with a comment character (#856 )
- [ ] Using `nrows=` could be parallel again by just issuing a (rare) warning if any out-of-sample type bumps occurred, since they could occur after the nrow'th row, as mentioned in PR #2623. This warning would be acceptable and would avoid extra code complexity and memory usage.
- [x] Should always warn when 'healing' quote rule is used, even in-sample.  And no need for warning if no quotes are in sample and then it bumps from rule 0 to rule 1 (unambiguous and robust). Follow up to #2265.
- [ ] fread should be able to parse data.table's printout (#2720)
- [ ] detect binary files as input, and issue proper error to the user (#2834)

## Feature requests (R)
- [x] allow fread to work on character vectors (#1423)
- [ ] if `select` is a list, then `colClasses` should accept a list of same length (#1426)
- [ ] allow colClasses for columns not present in the file (#1602)
- [ ] allow `stringsAsFactors` parameter to be a fraction between 0 and 1 (#2025)
- [ ] read feather files with fread (#2026)
- [ ] more flexible parameters `select` / `col.names` / `colClasses` (#2185, #2066, #491)
- [ ] Support UTF-16 encoded files (#2560)
- [ ] fread directly from the clipboard on windows (#1292 )
- [x] auto-detect and parse JSON fields within a CSV file (#1240)
- [ ] implement `sep2` (#1162)
- [ ] apply filtering function to detect which rows to read (#583 )
- [ ] add option to control destination for verbose messages (#775)
- [x] allow reading `.gz` files directly (#717)
- [ ] read multiple files (specified as a list or a glob) (#586, #2582)
- [ ] support reading files with more than 2B rows (#570)
- [ ] support file connections as an input source (#561)
- [ ] `drop` could drop all duplicated column names (e.g. many `"filler"` or `""` column names) (#1899)
- [x] Do not use curl::download in R 3.2.2+, since base::download.file is more robust (#1686)
- [ ] Parse date types natively (#1656, #1450)
- [ ] Check that colClasses have valid types (#1634)
- [ ] Skip sampling when all colClasses supplied (#3024)
- [ ] Free over-allocated space (#3025)
- [ ] fills character fields with empty strings or NAs (#2524)

## Miscellaneous
- [x] Performance test on huge CSV files (#2073)
- [x] Crash report on an .xz file (#1895)

```

                        open  closed
critical                   0       8
core bug                   8      32
bugs R                     4       6
                          ==========
                          12      46   /58
                                                   
feature requests (core)   16       8 
feature requests (R)      22       0
misc                       2       2
                          ==========
                          40      10   /50
```

**Comment by MichaelChirico** [comment]
+ #2423

**Comment by MichaelChirico** [comment]
Closing this, we can just track `label:fread` instead.
