### ISSUE TITLE
improvements to GL CI

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#3147]
- [x] rename jobs so shorter names will be more clearly visible in pipeline view
- [x] speed up / remove / split out `test-r-windows-devel` which now runs memory tests and takes almost an hour (#3208)
- [x] update linux builders from 3.4 to 3.5: pipeline https://gitlab.com/Rdatatable/data.table/pipelines/39599042 running on updated images
- [x] update devel win builder from old 3.6 to recent 3.6 (done, as can be seen https://gitlab.com/Rdatatable/data.table/-/jobs/132920745)
- [x] update rel win from 3.5.0 to 3.5.1 (#3203, done, see https://gitlab.com/Rdatatable/data.table/-/jobs/133230303)
- [x] "re-run" privileges for project members (https://gitlab.com/gitlab-com/support-forum/issues/4121)
- [x] cran build should fail on non-SUCCESS state
- [x] r-devel add `--enable-strict-barrier` flag when compiling R (done, as seen in build log: https://gitlab.com/jangorecki/dockerfiles/-/jobs/132644041)
- [x] fix `Compilation used the following non-portable flag(s): ‘-Wdate-time’ ‘-Werror=format-security’ ‘-Wformat’` (done, as seen in https://gitlab.com/Rdatatable/data.table/-/jobs/132997455)

**Comment by jangorecki** [comment]
r-devel image is now building R with `--enable-strict-barrier` thus job `test-dev-cran` now runs with `strict-barrier`

**Comment by jangorecki** [comment]
all resolved, closing.
