### ISSUE TITLE
Master list of most-requested issues

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#3189]
Redirecting from post at `/orgs/.../discussions`. Inspired by happening to notice an issue getting more support (through GitHub reactions) and borrowing the idea to scrape the GH API from [this](https://www.tidyverse.org/articles/2018/04/upvoting-issues/) nice article over at tidyverse. Here are all open issues with at least 5 positive reactions:

 - [ ] #635 - `[`
 - [ ] #3992 |`nafill`
 - [ ] #1639 |`on`
 - [ ] #2146 | `NEW`
 - [ ] #3957 | `NEW`
 - [ ] #1063 |`NEW`
 - [ ] #657 | `i`
 - [ ] #2778 | `froll`
 - [ ] #4970 | `NEW`
 - [ ] #3467 | `NEW`
 - [ ] #788 | `[`
 - [ ] #5621 | `DT()`
 - [ ] #4804 | `NEW`
 - [ ] #3241 | `froll`
 - [ ] #3739 |`uniqueN`
 - [ ] #1717 | `JOINS`
 - [ ] #599 | `JOINS`
 - [ ] #3721 | `JOINS`
 - [ ] #2879 | `NEW`
 - [ ] #2219 | `NEW`
 - [ ] #1700 | `JOINS`
 - [ ] #1543 | `:=`
 - [ ] #935 | `JOINS`
 - [ ] #857 | `JOINS`
 - [ ] #4697 | `ALTREP`
 - [ ] #4677 | `JOINS`
 - [ ] #4100 | `INTERNAL`
 - [ ] #4066 | `nafill`
 - [ ] #3815 | `GForce`
 - [ ] #3009 | `JOINS`
 - [ ] #3002 | `JOINS`
 - [ ] #1120 | `GForce`
 - [ ] #1086 | `NEW`
 - [ ] #5020 | `.SD`
 - [ ] #4572 | `NEW`
 - [ ] #3946 | `JOINS`
 - [ ] #3104 | `NEW`

-----

#### Fulfilled already

 - [x] #4348 | `INSTALLATION`
 - [x] #3060 | `NEW`
 - [x] #2181 | `JOINS`
 - [x] #2311 | `GForce`
 - [x] #4258 | `NEW`
 - [x] #3911 | `rbindlist` - [x] #2020 |`fwrite`| - fwrite ignores options(scipen = 999)
 - [x] #1886 |`transpose`| - feature request : transpose(keep.rownames = T)?
 - [x] #2016 - Support for writing to gzip (.gz) with fwrite
 - [x] #1878 - patterns in .SDcols
 - [x] #3042 - [FR] grouping in parallel
 - [x] #1708 - shift should accept negative n
 - [x] #1770 |`fwrite`| - fwrite UTF8
 - [x] #4247 | `DOCUMENTATION` | - Vignette for programmatic data.table (eval, get, etc)
 - [x] #3396 | `RESHAPING` | - melt.data.table should offer `variable` to match on the name, rather than the number
 - [x] #1828 |`NEW`| - [Request] data.table spark interface
 - [x] #2273 |`NEW`| - compatibility with sf library
 - [x] #4358 |`setcolorder`| - Additional arguments for setcolorder: before, after
 - [x] #2655 | `META` | - improvement on programmatically substituting columns in expressions
 - [x] #499 | `JOINS` | - [R-Forge <span>#</span>2461] Faster version of Reduce(merge, list(DT1,DT2,DT3,...)) called mergelist (a la rbindlist)
 - [x] #4152 | `NEW` | - "not in" operator `%!in%`
 - [x] #3977 | `GForce` | - GForce optimize weighted.mean
 - [x] #1414 |`GForce`| - GForce should be able to work with `:=` as well.
 - [x] #3795 |`:=`| - Add an alias for functional version of `:=`
 - [x] #795 | `.SD`
 - [ ] #1336 |`NEW`
 - [ ] #3670 | `INTERNAL`

Separately for `fread` since there are many:

 - [x] #2431
 - [ ] #583
 - [ ] #856
 - [ ] #1162
 - [ ] #711
 - [ ] #561
 - [ ] #4329
 - [x] #2691
 - [ ] #2714
 - [x] #1812
 - [ ] #1636
 - [ ] #1721

https://github.com/Rdatatable/data.table/issues?q=is%3Aissue%20state%3Aopen%20sort%3Areactions-%2B1-desc

**Comment by sritchie73** [comment]
GitHub recently introduced the ability to pin/sticky issues to the top of the list - I think this is appropriate for the master list of most requested issues

**Comment by grantmcdermott** [comment]
@MichaelChirico can you (or another dev) pin this issue to the repo? I think it would streamline a lot of searching for bug reports and help to limit dups.

**Comment by MichaelChirico** [comment]
Good idea, done!

**Comment by MichaelChirico** [comment]
Looks like the overhaul of GitHub issues is including a way to sort by reactions:

https://github.com/Rdatatable/data.table/issues?q=is%3Aissue%20state%3Aopen%20sort%3Areactions-%2B1-desc

I think it's still useful to keep this open, but might not be needed now that it's so easy to find what's most-requested?

**Comment by MichaelChirico** [comment]
Changing my mind -- we can easily find the most-requested issues now: (1) `top request` label (2) sort by `+1` reactions. No need to keep this in the tracker.
