### ISSUE TITLE
revdep PRs for := no recycling

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#3347]
Maintainers of the 16 packages affected were consulted before merging #3310 (see that PR for links to tweet and email etc). 13 replied all positively. 3 no-reply at the time of merge. 0 replies to disagree. That PR was merged and this issue is to submit PRs and track updates on CRAN.

13 CRAN :
(Check only when on CRAN so I know to mention the unchecked in the submission note.)
- [x] antaresViz:  https://github.com/rte-antares-rpackage/antaresViz/issues/177 (antaresRead v2.2.3; 13th Feb)
- [x] expss:  #3393 fixed on data.table side and maintainer notified that no action is needed
- [x] iml:  thanks @christophM (v0.9.0; 5th Feb)
- [x] irg:  https://gitlab.com/robit.a/irg/issues/23 (v0.1.1; 15th Feb)
- [x] popEpi:  https://github.com/WetRobot/popEpi/pull/148 (v0.4.6; 13th Feb)
- [x] rAmCharts:  https://github.com/datastorm-open/rAmCharts/pull/89 (v2.1.10; 12th Feb)
- [x] riskRegression:  thanks Thomas Alexander (v2019.01.29; 29th Jan)
- [x] scopr:  https://github.com/rethomics/scopr/pull/14 (v0.3.3; 14th Feb)
- [x] sdcTable:  thanks @bernhard-da for fixing https://github.com/sdcTools/sdcTable/commit/5d016c4d3bd60a516e7cf055c56d39623aad2c0b (v0.27; 28th Feb)
- [x] simstudy:  4 lines emailed to maintainer as not on GitHub.  (v0.1.12; 26th Feb)
- [x] vardpoor:  https://github.com/CSBLatvia/vardpoor/issues/18  (v0.14.0; 14th Feb)
- [x] multistateutils:  thanks @stulacy for updating on CRAN already! (v1.2.2; 4th Feb)
- [ ] POUMM:  https://github.com/venelin/POUMM/pull/2 and emailed maintainer

3 Bioconductor : 
- [x] dada2  (next release no longer uses data.table)
- [x] maftools:  https://github.com/PoisonAlien/maftools/pull/243
- [x] metagene:  https://github.com/CharlesJB/metagene/pull/117

**Comment by mattdowle** [comment]
All affected CRAN packages have updated now, other than POUMM. Have emailed maintainer and will mentioned in submission notes.
