### ISSUE TITLE
1.12.4 release checks

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#3863]
- [x] Rerun and resolve all revdeps #3581 
- [x] CRAN_Release.cmd (e.g. UBSAN, ASAN, rchk, gctorture, win-builder 2*OK)
- [x] win-builder R-devel seems to be stuck; emailed Uwe. r-release and r-oldrel are ok and pass ok.
- [x] CRAN 'additional issues': NoLD #3515, rchk #3867, and LTO #3864
- [x] one revdep fail (`segregation`) caused by #3895; tested and filed PR https://github.com/elbersb/segregation/pull/3; [update in v0.3.0 on CRAN 2019-09-20](https://cran.r-project.org/web/packages/segregation/index.html)
- [x] one revdep fail (`sensobol`) caused by #3891; just needs publish https://github.com/arnaldpuy/sensobol/issues/1; [update in v0.2.1 on CRAN 2019-09-20](https://cran.r-project.org/web/packages/sensobol/index.html)
- [x] Revisit test 1294.29 temporarily turned off in PR #3909
- [x] Final items in milestone
- [x] News item review and tidy
- [x] Codefreeze  ba63147c67ea228326eb6705126d4ad3062c2d2a
- [x] Repeat win-builder 3*OK
- [x] @renkun-ken go-first run please (last successful run: dc9a32a)
- [x] Final repeat CRAN_Release.cmd
- [x] Final rerun latest revdeps refreshed
- [x] Final repeat win-builder 3*OK
- [x] Submit to CRAN (several opportunities to halt after this)
- [x] CRAN pre-test success email received and OK
- [x] Bump dev version
- [x] Copy and paste revdep.R::status() output as new comment to this issue
- [x] CRAN revdep status impact results email received
- [x] Matt replied to confirm and explain differences to submission note
- [x] CRAN email received to confirm accepted
- [x] Add publish date to v1.12.4 title in NEWS.md
- [x] Update version and date in [Installation wiki](https://github.com/Rdatatable/data.table/wiki/Installation) heading
- [x] Tweet to #rdatatable. https://twitter.com/MattDowle/status/1179833079533203456

Based on 1.12.2 release check list: #3473

**Comment by MichaelChirico** [comment]
> Final low-risk items in milestone

Safe to say anything left on 1.12.4 milestone is targeted for this part? @mattdowle

**Comment by mattdowle** [comment]
Ideally yes. But that might change. Jan has done a great job postponing a lot already. #3890 is troubling and that's all I'm looking at currently.

**Comment by elbersb** [comment]
The new version of segregation is on CRAN, so that should be taken care of.

**Comment by mattdowle** [comment]
May thanks @elbersb!

@MichaelChirico Just on this 'release checks' issue, please don't edit the ticks. I was waiting to tick these two until they've fed through to my local revdep environment and passed for me locally. Which they have done now.

**Comment by mattdowle** [comment]
@renkun-ken Thanks for testing 4 days ago and updating the schedule above. I was watching and saw your updates: very useful. I just submitted to CRAN. If you have a chance to do a final go-first test would be great, and tick the box please. If you do find anything I can ask CRAN maintainers to halt the update.

**Comment by renkun-ken** [comment]
@mattdowle, I'm closely observing the progress and started running the production scripts with latest commit dc9a32a several hours ago. Hopefully, it will finish in a couple of hours.

**Comment by renkun-ken** [comment]
Everything looks good here.

**Comment by mattdowle** [comment]
Revdep status on submit:
```
CRAN:
 ERROR   :   1 : pmpp
 WARNING :   1 : optiSel
 NOTE    : 239
 OK      : 503
 TOTAL   : 744 / 744

BIOC:
 ERROR   :  10 : anamiR chimeraviz contiBAIT ENCODExplorerData GENESIS ImmuneSpaceR
                 ORFik Pviz SparseSignatures TitanCNA
 WARNING :  31 : AUCell BEARscc CellNOptR CONFESS crossmeta CytoML ELMER eQTL
                 flowWorkspace geneXtendeR GenoGAM genomation ggcyto HMMcopy iCNV
                 maftools methylPipe MinimumDistance MMAPPR2 MSnID MSstats netSmooth
                 openCyto pepStat QUALIFIER RegParallel RiboProfiling S4Vectors SISPA
                 TENxBrainData TFutils
 NOTE    : 109
 OK      :  37
 TOTAL   : 187 / 187

TOTAL          : 931
```
