### ISSUE TITLE
pkgdown todo list

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#3883]
Thread to gather issues spotted in new pkgdown website: https://rdatatable.gitlab.io/data.table

- [ ] missing current devel news at [changelog](https://rdatatable.gitlab.io/data.table/news/index.html) page (fixed by #3888)
- [x] links to manual (e.g. fwrite, fread) does not point to expected location (fixed by #3882)
- [ ] links mentioned above works fine in a website but not on README.md in github, we could put an absolute urls there maybe  - (fixed by #3888)
- [ ] `NA` title in a [contributing page](https://rdatatable.gitlab.io/data.table/CONTRIBUTING.html) that is linked from right side panel (fixed by #3888)
- [ ] Cheatsheet thumbnail appears broken - (fixed by #3888)
