### ISSUE TITLE
1.13.0 release checks

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#4606]
- [x] Rerun all revdeps: 
    already in error on CRAN with 1.12.8: `inlmisc` `mlr3proba` `Require` `rgbif` `strataG` `wyz.code.metaTesting`
    can't get `metaMix` past "Invalid MIT-MAGIC-COOKIE-1 key" locally
    `statcanR` fails locally with 1.12.8 on  "error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type"
    `skynet` fails locally with download problem https://github.com/ropensci/skynet/issues/6
    `traitdataform` fails locally with download problem, reruns same issue
    the following revdep errors are caused by data.table upgrade (just 9 packages out of 867 :+1:) : 
    (tick when either fixed in data.table, or we've heard from the maintainer ok to proceed)
- [x] eplusr #4612 
- [x] expss https://github.com/gdemin/expss/issues/67
- [ ] nc #4614 https://github.com/tdhock/nc/issues/15 and emailed
- [x] paradox #4607
- [x] popEpi #4615
- [x] socialmixr #4616
- [x] tableMatrix #4617
- [x] maditr https://github.com/gdemin/maditr/issues/14
- [x] memochange #4618 KaiWenger/memochange#13
- [x] CRAN_Release.cmd (e.g. UBSAN, ASAN, rchk #4625, gctorture #4628)
- [x] pass win-builder
- [x] CRAN 'additional issues' #4624
- [x] News item review and tidy
- [x] Codefreeze
- [x] @renkun-ken go-first run please (no error with aa608710cf0ec03c3c6cc3d7c03c96f2034ac856)
- [x] Repeat win-builder 3*OK
- [x] Start final rerun latest revdeps refreshed. CRAN runs revdep impact analysis as well before accepting, and they often find things I don't locally. Hence don't wait for this to complete.
- [x] Submit to CRAN (**several opportunities to halt after this, so please shout if something comes up**)
- [x] CRAN pre-test success email received and ok
- [x] Bump dev version
- [x] Copy and paste revdep.R::status() output as new comment to this issue
- [x] CRAN revdep status impact results email received
- [x] Matt replied to confirm and explain differences to submission note
- [x] CRAN email received to confirm accepted
- [x] Add publish date to v1.13.0 title in NEWS.md
- [x] Update version and date in [Installation wiki](https://github.com/Rdatatable/data.table/wiki/Installation) heading
- [x] Tweet to #rdatatable https://twitter.com/MattDowle/status/1286736488835801089
- [x] actel and spatsoc follow up https://github.com/hugomflavio/actel/issues/46 https://github.com/ropensci/spatsoc/issues/32

Based on 1.12.4 release check list: #3863

**Comment by mattdowle** [comment]
Revdep status on submit. Reasons in the top comment of this issue.

```
> status()
Installed data.table to be tested against: 1.13.0 2020-07-22 23:00:19 
CRAN:
 ERROR   :  12 : actel expss mlr3proba nc Require rgbif skynet spatsoc statcanR strataG traitdataform
                 wyz.code.metaTesting 
 WARNING :   2 : memochange metaMix 
 NOTE    : 292 
 OK      : 564 
 TOTAL   : 870 / 870 
 
BIOC:
 ERROR   :  19 : adductomicsR CATALYST cellbaseR cTRAP DMCFB DominoEffect ImmuneSpaceR LOLA LowMACA maser
                 methylPipe MouseFM PGA psichomics QuartPAC R3CPET rfaRm RGMQL TFutils 
 WARNING :  40 : artMS BEclear biscuiteer BrainSABER bsseq CellNOptR cicero cmapR CONFESS contiBAIT
                 crossmeta CytoML DiscoRhythm ELMER eQTL fcoex flowWorkspace geneplast geneXtendeR GenoGAM
                 genomation GenomicScores GmicR HMMcopy iCNV methrix MinimumDistance MMAPPR2 MSnID Onassis
                 phantasus pwOmics RiboProfiling S4Vectors sangeranalyseR SEtools signatureSearch SPONGE
                 TitanCNA ViSEAGO 
 NOTE    : 108 
 OK      :  40 
 TOTAL   : 207 / 207 
 
TOTAL          : 1077
```

actel and spatsoc were new in the final rerun I started at the same time as submitting to CRAN. They were not raised by CRAN's revdep checks so I did not halt CRAN release. Need to investigate those two.

I did not look at Bioconductor this time. There were repeated requests from Kurt and Uwe to update on CRAN as soon as possible because data.table's error status (caused by breaking change in R) was causing downstream issues. Bioconductor still has too many errors and warnings that collectively Bioconductor maintainers don't seem minded to fix for many years now despite me communicating many times with them.
