### ISSUE TITLE
1.13.4 release checks

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#4832]
Since the changes in this release were minimal I went for an accelerated approach: submitting to CRAN early since CRAN does revdep checking. I haven't received those results yet.
In the meantime I continued with local revdep testing, and a full refresh of my revdeplib, using R-release again instead of R-devel, for example (see commits to .dev).
Has now completed and there's just one impact (`akc`) due to `as.Date.IDate` no longer exported, news note 2.
```
CRAN:
 ERROR   :    4 : akc lava reproducible wyz.code.metaTesting 
 WARNING :    2 : bRacatus crfsuite 
 NOTE    :  330 
 OK      :  632 
 TOTAL   :  968 / 968 
```

[fail.log](https://github.com/Rdatatable/data.table/files/5639866/fail.log)

- [x] `akc`  due to `as.Date.IDate` no longer exported. PR submitted https://github.com/hope-data-science/akc/pull/4
- [x] `lava`  not due to data.table update as it occurs for me with 1.13.2 too https://github.com/kkholst/lava/issues/10
- [x] `reproducible`  same error `object 'split_chain' not found` on CRAN
- [x] `wyz.code.metaTesting`  same error `3L not equal to 2` as on CRAN unrelated to data.table, no change since https://github.com/Rdatatable/data.table/issues/4758
- [x] `bRacatus`  Same CRS warning occurs on CRAN so that's not due to data.table update https://github.com/EduardoArle/bRacatus/issues/3
- [x] `crfsuite`  not data.table related. gcc 10.2.0 locally appears to reveal a `-Wstringop-overflow` https://github.com/bnosac/crfsuite/issues/14

**Comment by eddelbuettel** [comment]
AFAICT you may not get rev.dep results because the package is already in state 'archived' which to the best of my knowledge means 'dead' whereas rev.dep results only come at the subsequent step(s).

```sh
edd@rob:~$ cranIncoming.r data.table        # simple littler wrapper for a foghorn function
    package version cran_folder                time    size
 data.table  1.13.4     archive 2020-12-01 19:15:00 5192530
edd@rob:~$ 
```

**Comment by mattdowle** [comment]
Thanks for looking. Email communication is ongoing with Uwe. He asked for some URL not-found to be fixed, and some URL-follows to be followed.  But they aren't not-found, and the follow suggestions aren't made by -as-cran, nor win-builder output, and I don't see why anyway.  So I asked him to proceed with submission as-is. I guess he'll un-dead it when he gets to it.

**Comment by eddelbuettel** [comment]
This is against `master` _right now_.  Do you want to PR this?

```r
edd@rob:~/git/data.table(master)$ urlUpdate.r -c    # Another littler wrapper
! Warning: DESCRIPTION:70:6 Moved
URL: http://r-datatable.com, https://Rdatatable.gitlab.io/data.table, https://github.com/Rdatatable/data.table
     ^~~~~~~~~~~~~~~~~~~~~~
     https://rdatatable.gitlab.io/data.table
! Warning: README.md:2:23 Moved
# data.table <a href="http://r-datatable.com"><img src="https://raw.githubusercontent.com/Rdatatable/data.table/master/.graphics/logo.png" align="right" height="140" /></a>
                      ^~~~~~~~~~~~~~~~~~~~~~
                      https://rdatatable.gitlab.io/data.table
! Warning: NEWS.md:865:546 Moved
13. Multithreaded stability should be much improved with R 3.5+. Many thanks to Luke Tierney for pinpointing a memory issue with package `constellation` caused by `data.table` and his advice, [#3165](https://github.com/Rdatatable/data.table/issues/3165). Luke also added an extra check to R-devel when compiled with `--enable-strict-barrier`. The test suite is run through latest daily R-devel after every commit as usual, but now with `--enable-strict-barrier` on too via GitLab Pipelines ("Extra" badge at the top of the data.table [homepage](http://r-datatable.com)) thanks to Jan Gorecki.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 https://rdatatable.gitlab.io/data.table
! Warning: man/fwrite.Rd:64:245 Moved
\code{fwrite} began as a community contribution with \href{https://github.com/Rdatatable/data.table/pull/1613}{pull request #1613} by Otto Seiskari. This gave Matt Dowle the impetus to specialize the numeric formatting and to parallelize: \url{https://blog.h2o.ai/2016/04/fast-csv-writing-for-r/}. Final items were tracked in \href{https://github.com/Rdatatable/data.table/issues/1664}{issue #1664} such as automatic quoting, \code{bit64::integer64} support, decimal/scientific formatting exactly matching \code{write.csv} between 2.225074e-308 and 1.797693e+308 to 15 significant figures, \code{row.names}, dates (between 0000-03-01 and 9999-12-31), times and \code{sep2} for \code{list} columns where each cell can itself be a vector.
                                                                                                                                                                                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                                                                                                                                                    https://www.h2o.ai/blog/fast-csv-writing-for-r/
! Warning: man/fread.Rd:132:6 Moved
\url{https://www.cerebralmastication.com/2009/11/loading-big-data-into-r/}\cr
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     https://cerebralmastication.com/2009/11/loading-big-data-into-r/
edd@rob:~/git/data.table(master)$ 
```

**Comment by mattdowle** [comment]
The very point of r-datatable.com is to be a forward to the current homepage. It's the canonical short URL for data.table's homepage that doesn't change over the years.
The two blog articles 'moved' don't appear for me or on win-builder. Instead I see 96 too-many-request messages. Those two work, and the blog admins might change the redirect in future. Since they aren't shown by win-builder output, nor locally for me, I think the pragmatic thing to do is let the submission proceed as-is.

**Comment by eddelbuettel** [comment]
Sure, you think is best.  But note that you missed

- a http -> https change in the first two; that is something hard to argue with as https *is* preferred
- an apparent www.* -> * URL change, those happen, so why argue

I'd just make the change.  I wasted so much time back and forth with them on these changes which, as Kurt and I *eventually* figured out, have to do with the package `xml2` installed or under your r-devel.  Mine didn't have it so I never got his results.  The new contributed url checker package helps, so I use it.

**Comment by eddelbuettel** [comment]
> I am frustrated 

@joshuaulrich and I actually tried to sort this out with Uwe and Kurt and got nowhere because it is a rather obscure test setup, and the non-reproducibility drove me bonkers.  So I am glad I now have a third-party tool that dug through their code, replicated it and allows me to deal with this proactively.  

It's still a shame this is not tied in a portable fashion into `R CMD check` but as some disciplines teach us, we do live in a second-best world so ... :man_shrugging:

**Comment by mattdowle** [comment]
I didn't miss the http. The provider, DomainMonster, does not provider forwarding for https. They only provide a http domain which forwards.
> an apparent www.* -> * URL change, those happen, so why argue
Because it wasn't flagged by win-builder before release. I don't mind doing that one for next release. Why argue with me, and not just let the submission proceed?

> xml2 installed or under your r-devel. Mine didn't have it so I never got his results.
I am so aware of that, it hurts. See long standing comments and procedures in CRAN_Release.cmd. That is not why it doesn't come up for me.  Note that win-builder doesn't come up either, and that's doing the checking with xml2.  It's probably because of the 96 too-many-requests problem, because of declining my suggestion to add github.com to a whitelist.

**Comment by eddelbuettel** [comment]
> I didn't miss the http. The provider, DomainMonster, does not provider forwarding for https. 

Maybe say hello to 2020 and move the content elsewhere?  I am happy as a clam with GitHub for hosting, including CNAME records.  My [stat430.com](https://stat430.com) is one and it does https.  For free.

**Comment by eddelbuettel** [comment]
And I am not trying to argue with, I started to try to help to point out that your package is actually in archived.

CRAN drove me mad too this year, but they mean well and are simply (by the shocking lack of an ability to scale or delegate) even _more_ stressed than you and me.  So my strategy now is to get the number of NOTEs and WARNINGs down to zero.  At whatever cost,  If a test blows up for no apparent reason at their end, I will consider to just remove it.  Not the best engineering practive but I just don't have the time or patience for the back and forth.  And the three day gaps between emails.

Anyway, peace out.  You have this under control.  Looking forward to seeing 1.13.4 on CRAN one of these days.

**Comment by mattdowle** [comment]
The content is not on DomainMonster.  It is just a forward. If you know of a service or method to create https://r-datatable.com which forwards to the current homepage which is https://rdatatable.gitlab.io/data.table/, and I hope you consider is 2020-worthy and we are happy as a clam with too, then please let me know.

**Comment by eddelbuettel** [comment]
PS I did get the 'TOO MANY REQUESTS' issue solved (for github) by (eventually) making Kurt understand what GITHUB_PAT is, and to have it applied on his box.  That knowledge has not yet made to Dortmund so you win some and leave with scoreless draw in other matches.  _C'est la vie._

**Comment by eddelbuettel** [comment]
Hml I use [gandi](https://gandi.net) for my all my domains (and have since, if memory serves, the last 1990s), and it offers basic  dns control -- which lets you point to machines which will then use CNAMES to respond. I forget the details but this is AFAIK very standard fare, but maybe one step in complexity from basic forwarding.  It is happens that GitHub works well with that by letting you (easily) set a CNAME (as a file in the repo, could not be easier).  I never used GitLab for this so cannot help on that end.

**Comment by mattdowle** [comment]
I've asked Gandi support, ticket 13231255, as follows:
> Hi,
> My domain, r-datatable.com, is currently hosted by DomainMonster. I use it simply for web forwarding.  It redirects to my project's current homepage which is hosted on GitLab and I'm happy with.
> But, DomainMonster can only forward http://r-datatable.com. Not https, i.e. https://r-datatable.com. If you try the https version you should find that it doesn't work.
> If I moved my domain to you, can you make https://r-datatable.com work and forward to https://rdatatable.gitlab.io/data.table/?  Just like http://r-datatable.com already does.
> Thanks, Matt

**Comment by eddelbuettel** [comment]
Nice.  They are of course a web-based firm with many low-priced products so not sure how much you will get from support.

Forward, which you asked for, surely exists.  It is however not what I use. I tend to use explicit DNS setup which they also offer.  A little more complicated.  Generally more flexible.  Happy to help with either.   "Just DNS" for a domain is still cheap (couple bucks a year(,

**Comment by eddelbuettel** [comment]
PS Looks like I was wrong about one aspect above.  Checking an updated package I am currently preparing with my local r-devel build I now (at last !!) get the checks locally too which I otherwise only got from win-builder (where they'd also be masked by the all the 'too many requests' false positives from GH).  So some progress.   And thank you making the changes!

**Comment by mattdowle** [comment]
I submitted a working tested patch to Uwe to whitelist GH, years ago. He declined it for the reason of not wanting to maintain a whitelist. And here we still are.

**Comment by eddelbuettel** [comment]
Yes. Their inability with respect to scaling and delegation is beyond maddening. 

I argued for generalized white-lists (as _e.g._ Debian's `lintian` tool supports) multiple times on the list(s) but gave up.  Ditto with their inability to even communicate policy changes (which lead to the very blunt bot watching changes in CRAN Repo Policy).

Given the reach and visibility they have, it is way beyond absurd.  Yet, as you say, "here we still are".

**Comment by mattdowle** [comment]
You have mentioned lack of delegation before. Who is offering to be delegated to?  And scaling is a bit vague.
"generalized white-lists (aka lintian)"?  That turns a molehill into a mountain and kills any hope of getting it done.
KISS

My patch was simple and self contained. That maintaining a whitelist being difficult or time consuming was a concept that should never have been entertained. Very likely, it would have been one line, github.com, as my patch contained, and no others would have needed to be added. Maybe one or two more, but I don't know of any. There was no good reason to think that maintaining a whitelist would be time consuming. It was just plucked as a reason given a no-can-do, not-invented-here attitude. That's at least, as far as I can tell, given minimally-worded emails we consider ourselves lucky if we get a reply at all.

**Comment by eddelbuettel** [comment]
Generalized white-list works _great_.  Look at the `lintian` package you could install on your Ubuntu box, and in the `debian/` directory and just about _any_ package (all web-browsable at source.debian.org, _e.g._ here is the one for [r-base-core](https://sources.debian.org/src/r-base/4.0.3-1/debian/r-base-core.lintian/)).  As for lack of delegation, offers have been made, some folks had joined and later left; others are less active.  Not my role to wash this laundry in public but let's just say that it does aways take two to tango.

So let's not argue with each other. I think we agree in principle that the status quo is far from ideal, has been for a while and nuttin' changes.  Funny, that.

**Comment by mattdowle** [comment]
I think we need a solution to the too-many-request that works for all package maintainers; i.e., something that is included when we run `R CMD check --as-cran` ourselves locally before submitting to CRAN. Whether we are running Linux, Windows or Mac. I looked at your link and `lintian` but as far as I can see it is Debian-only.  I can see why that proposal did not fly with the CRAN maintainers.

**Comment by eddelbuettel** [comment]
We are mixing a few topics. While it's late let me briefly hit a few.

First, 'too many requests' at GitHub is no longer an issue if you just set an env var as `Sys.setenv("GITHUB_PAT"="my personal github pat here")` (or in another way to set an env.var..  It's really between the user and GH and out of CRAN's control as _per-user_ experience.

Second, `lintian` was a working example just to show what can be done. As I mentioned I used it in the past as reference point; these discssions went nowhere and I consider white lists at CRAN dead.  Which I consider a mistake, but sadly not something I can change. 

Third, I am indeed an R Foundation Board member and may or may not been aware or involved in related proposals, but beyond what it is in the (public) minutes I cannot discuss anything. 

Lastly, as I may not have been to successful in expressing in these threads, I am currently not to hopeful that any of this will change for better any time soon.  Which is why I am glad you are changing these redirect URLs and moving on.

**Comment by mattdowle** [comment]
I have always changed redirect URLs in the past, moved-on, kept my head down, and just-done-it, for years now. I didn't need that advice. As I wrote, the problem has indeed been too-many-requests resulting in redirects not being shown to me before submission, resulting in me creating a patch to solve the problem. That patch being declined with no solution, and problems continuing for years, has been the issue.  Sometimes I do see the URL problems in the output, mixed in with the too-many-requests, I guess depending on where NEWS.md comes in the order of testing all URLs.  So I have trawled through the too-many-requests manually by eye and just-done-it for the real ones I can find. For years now. Over and over again. I submitted a patch to Uwe and it was declined.  So I then had to resort to splitting up NEWS.md into NEWS0.md for the sole reason of this issue. You do not need to tell me to just-do-it, Dirk.

The 3 not-found URLs are still not found on Uwe's side, but I see no problem with them. They work consistently here and are just links to pdf files on github which haven't changed, and they are our pdfs. Again I've asked him to accept the revised submission, which may well be currently marked dead again.

Finally we have a solution: `Sys.setenv("GITHUB_PAT"="my personal github pat here")`.

For future reference, when you wrote this earlier above :

> PS I did get the 'TOO MANY REQUESTS' issue solved (for github) by (eventually) making Kurt understand what GITHUB_PAT is, and to have it applied on his box. That knowledge has not yet made to Dortmund so you win some and leave with scoreless draw in other matches. C'est la vie.

I don't know. The wording. So I didn't follow up on it at the time. I'll do that locally and, as always, add it to CRAN_Release.cmd so that, at least on the data.table, the information is shared. Thank you!  I will also email Uwe and make sure he is aware of the solution so that win-builder's too-many-requests can be fixed.

**Comment by eddelbuettel** [comment]
I stop now as you continue to misread and misconstrue what I wrote. _I am not arguing with you, I am commisserating with you_.

**Comment by mattdowle** [comment]
If you write "Which is why I am glad you are changing these redirect URLs and moving on."  Then that's arguing with me.  Because that's not what I'm doing.  I did change the URLs but I ddn't move on.  I continue to fix the root cause.
Again, thank you!  I wrote to Uwe to ensure he knows about the too-many-requests fix and can apply it to win-builder.
