### ISSUE TITLE
revdep status

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#4866]
There are a few more revdeps failing on CRAN currently than normal. I double checked they are not failing due to data.table by testing them using data.table v1.13.4 and the same errors occur, as expected given revdep checks before release.
Logging here as an issue so we have a line in the sand as development on the next release progresses, and to inform in case anyone thinks CRAN errors are due to the data.table update.
New function to report cran status of the failing revdeps added in deac792a9081d879aba4c027399b8e794a1f57d9.
In a month if the revdeps are still failing on CRAN we could start gentle nudging.

```
 ERROR   :   13 : bigsnpr BuyseTest covidregionaldata datagovsgR datapackage.r grattan lava optiSel
                  r2dii.match restatapi spocc wyz.code.metaTesting xgboost 
 WARNING :    2 : causalCmprsk crfsuite 
 NOTE    :  328 
 OK      :  637 
 TOTAL   :  980 / 980

tools::CRAN_check_results() returned 201,652 rows in 5.805s elapsed (1.063s cpu) 
R-release is used for revdep checking so comparing to CRAN results for R-release
                 Package r-release-linux-x86_64 r-release-macos-x86_64 r-release-windows-ix86+x86_64
 1:              bigsnpr                  ERROR                   NOTE                            OK
 2:            BuyseTest                  ERROR                   NOTE                            OK
 3:    covidregionaldata                  ERROR                   NOTE                         ERROR
 4:           datagovsgR                  ERROR                     OK                         ERROR
 5:        datapackage.r                  ERROR                   NOTE                         ERROR
 6:              grattan                  ERROR                   NOTE                          NOTE
 7:                 lava                   NOTE                     OK                            OK
 8:              optiSel                  ERROR                   NOTE                          NOTE
 9:          r2dii.match                  ERROR                     OK                         ERROR
10:            restatapi                  ERROR                     OK                         ERROR
11:                spocc                  ERROR                     OK                            OK
12: wyz.code.metaTesting                     OK                     OK                         ERROR
13:              xgboost                  ERROR                   WARN                         ERROR
14:         causalCmprsk                   WARN                     OK                          WARN
15:             crfsuite                     OK                     OK                            OK
```

[fail.log](https://github.com/Rdatatable/data.table/files/5762253/fail.log)

Of these, 3 packages are ok on CRAN r-release-linux but error/warn just locally for me:
- [x] `lava`  seen before in #4832  kkholst/lava#10
- [x] `wyz.code.metaTesting`  seen before in #4832 and #4758. The same error `3L not equal to 2` that I see locally occurs on CRAN just on WIndows.  neonira/wyz.code.metaTesting#1
- [x] `crfsuite`  seen before in #4832  bnosac/crfsuite#14

It seems that r-release-macos-x86_64 is using R 4.0.2 not R-release which is R 4.0.3.  Since that column for macos is largely ok above, perhaps 4.0.2 vs 4.0.3 is in play too. Anyway, that's for those packages to investigate.

**Comment by privefl** [comment]
Hi, where could I find the detailed errors for my package {bigsnpr}?

Best

**Comment by MichaelChirico** [comment]
you can start at the CRAN results page:

https://cran.r-project.org/web/checks/check_results_bigsnpr.html

ideally you could reproduce the same error by installing the CRAN versions
of your package & all dependencies locally; barring that, you can try using
r-hub to do so

**Comment by privefl** [comment]
Ok, seems the ERRORs are on me, and have nothing to do with {data.table}.
I'll try to fix them when I have some time.

**Comment by mmatyi** [comment]
Hello,

a new version (0.9.8) of the `restatapi` is just uploaded to CRAN. It should resolve the error.

**Comment by mattdowle** [comment]
Thanks all!

I had sent the email below to `sapply(.fail.cran, maintainer)` (15 packages above) which is why we're hearing from them here.

It really helps in revdep testing of data.table (980 packages) when the packages are passing OK on CRAN so that we can see that the error/warning is caused by the data.table update. We don't have the logic in place to count the number of warnings and errors on CRAN to see if the data.table update would increase the number of warnings or errors.  And even if we did do that work, there could be a situation that the data.table update would cause a different error or warning with the count of warnings and errors unchanged. So it's much easier for me if the revdeps are passing on CRAN all OK, and then I know it's the data.table update that has caused any problem. Similarly, R-core maintainers use CRAN as a giant test suite to know if their changes to R-devel have caused any problems to any CRAN package. If the CRAN package is already in error or warning status they don't see the change in status and can miss the impact.

---

Hi all,

First of all, happy new year!

Just to let you know that your package is in either error or warning
status when I test packages which use data.table. Your package appears
here:  https://github.com/Rdatatable/data.table/issues/4866

Please could you resolve the problem as soon as possible within the
next few months.

Best,
Matt

---

**Comment by kleanthisk10** [comment]
Hello everyone,

Happy new year!
Thank you for noticing. I am also aware of this issue and I will fix my package as soon as possible. 
CRAN package submissions were closed until yesterday.

Best,
Kleanthis

**Comment by privefl** [comment]
{bigsnpr} should be fixed now (it was due to some update in {Matrix}.

**Comment by mattdowle** [comment]
Current revdep status.  Thanks to everyone for updating!
```
CRAN:
 ERROR   :    2 : lava segregation 
 WARNING :    1 : crfsuite 
 NOTE    :  346 
 OK      :  650 
 TOTAL   :  999 / 999 
```

**Comment by mattdowle** [comment]
Those 3 (lava, segregation & crfsuite) are now resolved too.  Thanks again to everyone.

Current status shows new problems showing on CRAN too which are just normal and recent non-data.table regular issues. So closing this issue now.

```
> status()
 ERROR   :    2 : reproducible rGoodData 
 WARNING :    2 : disk.frame tcR 
 NOTE    :  350 
 OK      :  654 
 TOTAL   : 1008 / 1008

> cran()
tools::CRAN_check_results() returned 204,158 rows in 12.1s elapsed (1.021s cpu) 
R-release is used for revdep checking so comparing to CRAN results for R-release
        Package r-release-linux-x86_64 r-release-macos-x86_64 r-release-windows-ix86+x86_64
1: reproducible                  ERROR                     OK                         ERROR
2:    rGoodData                  ERROR                     OK                         ERROR
3:   disk.frame                   WARN                     OK                          WARN
4:          tcR                   WARN                   NOTE                          WARN
```

**Comment by mattdowle** [comment]
Current status just before releasing 1.14.0. Never seen it cleaner.
```
> status()
 ERROR   :    0 :  
 WARNING :    1 : tcR 
 NOTE    :  350 
 OK      :  665 
 TOTAL   : 1016 / 1016 
 
> cran()
tools::CRAN_check_results() returned 205,020 rows in 6.796s elapsed (1.100s cpu) 
R-release is used for revdep checking so comparing to CRAN results for R-release
   Package r-release-linux-x86_64 r-release-macos-x86_64 r-release-windows-ix86+x86_64
1:     tcR                   WARN                   NOTE                          WARN
```
