### ISSUE TITLE
Vignettes

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#944]
#### HTML vignette series:

**Planned for `v1.9.8`**
- [ ] Quick tour of data.table
- [x] [Keys and fast binary search based subset](https://rawgit.com/wiki/Rdatatable/data.table/vignettes/datatable-keys-fast-subset.html)
- [x] [Secondary indices and auto indexing](https://rawgit.com/wiki/Rdatatable/data.table/vignettes/datatable-secondary-indices-and-auto-indexing.html)
- [x] **Joins vignette**. a) _joins_ vs _subsets_ -- extending binary search based subset to joins + conditional / non-equi joins, rolling and interval joins. b)  by=.EACHI, join + update feature. c) Document `i.col` usage as filed in #1038. d) Also cover about performance/advantages from #1232. 
- ~~[ ] Cover `get()` and `mget()`. E.g., http://stackoverflow.com/q/33785747/559784~~ covered in #4304
- [ ] Add about on= argument rationale in FAQ (#1623).
- [ ] FAQ 5.3 needs to mention that it's a _shallow_ copy that's done in order to restore over-allocation. Thanks to Jan for linking it in #1729.

---

**Future releases**
- [ ] data.table internals, performance aspects and _expressiveness_
- [ ] Reading multiple files (`fread` + `rbindlist`), ordering, ranking and set operations
- [ ] IDateTime vignette
- [ ] Document the difference between `data.table()` and `data.frame()` somewhere - relevant issues: #968, #877. Perhaps slightly more in detail in the FAQ.
- [ ] coursera FAQ
- [ ] Advanced `data.table` usage: 
  - [ ] NSE
  - [ ] ...
- [ ] Timings vignette (moving #520 here to get everything in one place, but not sure if we need it as a vignette since we've the Wiki with benchmarks/timings).
- [ ] `fread+fwrite` vignette, include also [Convenience features of fread](https://github.com/Rdatatable/data.table/wiki/Convenience-features-of-fread) wiki, also https://github.com/Rdatatable/data.table/issues/2855

---

**Finished:**
- [x] [Introduction to data.table](https://rawgit.com/wiki/Rdatatable/data.table/vignettes/datatable-intro-vignette.html) - data.table syntax, general form, subset rows in `i`, select / do in `j` and aggregations using `by`.
- [x] [Reference Semantics](https://rawgit.com/wiki/Rdatatable/data.table/vignettes/datatable-reference-semantics.html) (_add/update/delete_ columns by reference, and see that we can combine with `i` and `by` in the same way as before)
- [x] [Efficient reshaping using data.tables](https://rawgit.com/wiki/Rdatatable/data.table/vignettes/datatable-reshape.html)
- [x] Link to [this answer on SO](http://stackoverflow.com/a/27004566/559784) on `by=.EACHI` until the vignette is done.

---
#### Minor:
- [ ] Operations using `integer64`, and promoting it for _large integers_.

---

Notes (to update current vignettes based on feedbacks): Please let me know if I missed anything..
#### Introduction to data.table:
- [x] `order` in `i`.
- [x] Explain how to name columns in `j` while selecting/computing.
- [x] Emphasise that _keyby_ is applied _after_ obtaining the result on the computed result, not on the original data.table.
- [x] Mention new updates to `.SDcols` and cols in `with=FALSE` being able to select columns as `colA:colB`.
#### Reference semantics:
- [ ] Also explain all other relevant `set*` functions here.. (`setnames`, `setcolorder` etc..)
- [ ] Mainly `set`.
- [x] Explain that `1b) the := operator` is just defining ways to use it - the example there doesn't work as it just shows two different ways of using it -- Following [this comment](http://stackoverflow.com/questions/29870673/how-to-unquote-string-in-r-to-access-column-in-data-frame?noredirect=1#comment47913441_29870673).
#### Keys and fast binary search based subsets:
- [ ] Add an example of subset using integer/double keys.
- [ ] Difference in "nomatch" default in binary search based subsets.
- [ ] replacing NAs with binary search based subsets possible?
#### FAQ (most appropriate here, I think).
- [x] Update FAQ with issue on external pointer being NULL when reading an R object from file, for example, using `readRDS()`. Update [this SO post](http://stackoverflow.com/q/29614386/559784).
- [ ] Explain with example, on over allocating the data.table using `alloc.col()`, and when to use it (when you need to create multiple columns), and why. Update [this SO post](http://stackoverflow.com/q/29615181/559784).

**Comment by arunsrinivasan** [comment]
I've finished the *Introduction to data.table* vignette (see link on top). It'd be great to know what you think.

Thanks to @jangorecki and @brodieG for great feedbacks, and of course @mattdowle :-).

**Comment by markdanese** [comment]
This is really great.  Wish it existed a year ago when I started using data.table.  A couple of small things below for your consideration:
You might want to mention that you can sort (via `order`) in `i` in your summary at the end.  You could also want to mention this at the beginning.  You could also mention that there are more sophisticated joins that can be done in `i` involving keys that are not covered.  That allows you to mention the main functions of `i` so the reader can look for more advanced functions if they need them.  And you can hyperlink to them later.

In the .SD section you write "that group" but it might be more clear to say "that group defined using `by`".  This is also done a little later as well.

I might have missed it, but it would be good to be a little more clear that `.SD` with `by` essentially limits the data to the .SD columns and then creates a set of data.tables for each unique combination of the variables in the `by`.  It then processes these data.tables in the order of the `by` variables using the function(s) from `j`.  You could even mention that there are special symbols that allow users to access some of the indexes generated as part of that processing, but that these are beyond the scope of the introduction vignette.

Again, these are just suggestions.  Your hard work (and Matt's) is greatly appreciated.

**Comment by arunsrinivasan** [comment]
On Sat, Jan 17, 2015 at 6:22 PM, Mark Danese <notifications@github.com>
wrote:

> This is really great. Wish it existed a year ago when I started using
> data.table. A couple of small things below for your consideration:
>
Thank you.

> You might want to mention that you can sort (via order) in i in your
> summary at the end. You could also want to mention this at the beginning.
>
Oh snap! Great point. I should add "order(..)" at the very beginning, and
will add to summary as well.

> You could also mention that there are more sophisticated joins that can be
> done in i involving keys that are not covered. That allows you to mention
> the main functions of i so the reader can look for more advanced
> functions if they need them.
>
Right, will do.

> And you can hyperlink to them later.
>
That, I'm not sure.. as these are meant to be pushed to CRAN, and as well
on the WIKI..

> In the .SD section you write "that group" but it might be more clear to
> say "that group defined using by". This is also done a little later as
> well.
>
I thought I edited it out to "the current group", but apparently not.. "by
the current group columns specified in `by`" - how does that sound?

> I might have missed it, but it would be good to be a little more clear
> that .SD with by essentially limits the data to the .SD columns and then
> creates a set of data.tables for each unique combination of the variables
> in the by. It then processes these data.tables in the order of the by
> variables using the function(s) from j.
>
I think you missed it. It is right underneath the block quote where .SD is
explained (in section 2e). And it explains exactly what you mention here...

> You could even mention that there are special symbols that allow users to
> access some of the indexes generated as part of that processing, but that
> these are beyond the scope of the introduction vignette.
>
Right.. that's the reason for not introducing the other special symbols.

> Again, these are just suggestions. Your hard work (and Matt's) is greatly
> appreciated.
>
Great suggestions. I'll write back once I've the other vignettes uploaded.

**Comment by jangorecki** [comment]
> That, I'm not sure.. as these are meant to be pushed to CRAN, and as well
on the WIKI..

When you push package to CRAN which includes `Rmd` in `vignettes` directory they will be build and available on CRAN as rendered html. CRAN is a good place for vignettes as for many users it is the first place to seek for docs/tutorials.

**Comment by brodieG** [comment]
>> And you can hyperlink to them later.

> That, I'm not sure.. as these are meant to be pushed to CRAN, and as well on the WIKI..

Don't single folders link on CRAN?  I haven't actually put anything up there, but **[this vignette](http://htmlpreview.github.io/?https://raw.githubusercontent.com/brodieG/unitizer/master/inst/doc/vgn01introduction.html)** links multiple others in the same folder by using relative links and works fine from R.

**Comment by arunsrinivasan** [comment]
Updated with *Reference Semantics* vignette.

**Comment by markdanese** [comment]
thanks again for doing all of this.  

just one other suggestion on something to cover on a vignette -- using data.table inside your own function.  not writing a package, but just trying to automate some common tasks.  there are some tricks that I have not quite figured out.  also if there is a post somewhere on this topic, a link would be appreciated. 

finally, a vignette listing "useful" stack overflow posts might be helpful for topics you don't want to include in a vignette.

just some random thoughts.

**Comment by juancentro** [comment]
Two thoughts :
- Link to the vignettes in the wiki
- In the reference semantics vignette, add how to use := with a quoted list expression (or just a quoted assignment). Maybe this deserves its own vignette, as the NSE (non standard evaluation) in data.table eases interactive use but requires that for using data.table in your own function or package you should now something about quote, eval, substitute and friends. Maybe just add something like dt[,  do.call(":=", eval(my_quoted_list)] to the vignette and then create a vignette on NSE and its implications?

**Comment by arunsrinivasan** [comment]
Thanks.

1. Have you seen [this](https://github.com/Rdatatable/data.table/wiki/Getting-started)?
2. That'll most likely be covered in a separate vignette. But no plans yet.

**Comment by juancentro** [comment]
@arunsrinivasan Nope, I hadn't seen that, great! Another bookmark

**Comment by arunsrinivasan** [comment]
Updated with *Keys and fast binary search based subset* vignette.

**Comment by markdanese** [comment]
Very nice.  I love these vignettes.  Just some quick comments for consideration.

What is the purpose of taking over row names if they are not used?  Or are they used by the special operators in j (like .N, .I, etc.)?  I think they are used by data.table, but just not as indices.  I have always been confused by the purpose of forcing the numbered row names.

Why use `unique` in the first key when accessing only the second?  If you don't, you get a lot of repeated rows in the output, right?  Maybe obvious, but it might be helpful to say/show what happens if you don't.

Do all keys need to be quoted?  Even numeric (integer) ones?  Can you use a numeric as a key?  Any things to watch out for?

What if your key column has NA in it?  Can you search for those and replace them (as you did in your example where your replaced 24 with 0?

It might help to explain that `keyby` applies to the *output* data.table (`ans` in your example) and not the input data.table (`flights` in your example).

Can you pass a vector to the key?  In other words, can you create `airport` <- c("LGA", "JFK", "EWR")` and use `airport` directly in `i` in your example near the bottom?  This might help set up the idea of passing a different data.table in for a merge.

Typo on "corresponding" ("correspondong").  One of the back ticks is missing in the vector scan section where you writing "The row indices corresponding to origin == "LGA" anddest == “TPA”` are obtained using key based subset."

**Comment by jangorecki** [comment]
@markdanese regarding the
> Why use unique in the first key when accessing only the second?

```r
flights[.(unique(origin), "MIA")]
```
Not sure if you very asking to suggest better explanation or you are not aware of more complex usage of multiple column key.
You cannot simply use binary search on `dest` when your key is `c(origin, dest)`, you should have `c(dest, origin)` to use binary search on `dest`. Using `.(unique(origin), "MIA")` uses binary search, by providing all available values for the first column in key and then selective values to second column.
I've made an extension to use only selective columns from key. looking at the [simple example](https://github.com/jangorecki/dwtools#idxv) may also help you to understand. My extension is not ready to be PR to data.table master as the memory usage does not scale as good as it could if developed using internal data.table functions / combined with data.table secondary key.
> Can you use a numeric as a key?

You can use numeric as key, it is mentioned in `Keys and their properties`.
> Any things to watch out for?

Not sure but `setNumericRounding` affects the numeric key, might be worth to mention in the vignette.

> What if your key column has NA in it? Can you search for those and replace 

Assuming the `is.na()` is optimized to use binary search then answer is *yes*. Looking at #889 I assume it is already optimized.

Also to @arunsrinivasan, the typo in:
> find the matching vlaues in

**Comment by markdanese** [comment]
Thanks Jan -- that is really helpful.  I offered those questions as things that could briefly be mentioned in the vignette to help new users understand what is going on.  They were things that came to mind (as a fairly new user) while reading the documentation.  I can't really contribute to the code, so I am hoping to contribute by helping with the documentation.

**Comment by arunsrinivasan** [comment]
On Fri, Jan 23, 2015 at 8:48 PM, Mark Danese <notifications@github.com>
wrote:

> Very nice. I love these vignettes. Just some quick comments for
> consideration.
>
> What is the purpose of taking over row names if they are not used? Or are
> they used by the special operators in j (like .N, .I, etc.)? I think they
> are used by data.table, but just not as indices. I have always been
> confused by the purpose of forcing the numbered row names.
>
Section 1a, just above Keys and their properties has answer to this.
Data.tables *inherit* from data.frames.

> Why use unique in the first key when accessing only the second? If you
> don't, you get a lot of repeated rows in the output, right? Maybe obvious,
> but it might be helpful to say/show what happens if you don't.
>

Again, this is explained exactly underneath in "what's happening here?". I
even refer to the previous section where I lay the groundwork for
explaining this one.


> Do all keys need to be quoted? Even numeric (integer) ones? Can you use a
> numeric as a key? Any things to watch out for?
>
There's an example with integer columns on 2d. I thought that was
sufficient?

> What if your key column has NA in it? Can you search for those and replace
> them (as you did in your example where your replaced 24 with 0?
>
Good point. That's a difference with vector scan. Will try to add this.

> It might help to explain that keyby applies to the *output* data.table (
> ans in your example) and not the input data.table (flights in your
> example).
>
'keyby' was already discussed in the first vignette. But I'll see if this
can be added.

> Can you pass a vector to the key? In other words, can you create airport
> <- c("LGA", "JFK", "EWR")and useairportdirectly ini` in your example near
> the bottom? This might help set up the idea of passing a different
> data.table in for a merge.
>
Content for next section. That is how we transition into joins.

> Typo on "corresponding" ("correspondong"). One of the back ticks is
> missing in the vector scan section where you writing "The row indices
> corresponding to origin == "LGA" anddest == “TPA”` are obtained using key
> based subset."
>
Thanks.

**Comment by smartinsightsfromdata** [comment]
Great work on these vignettes!
My comments may be late or already covered:
* I would like to see a variety of ways / examples of using dynamic rows and columns.
* More extensive comparison on merge and joins.
* Different / richer ways to use ```set```.  Also, it would be nice to see an explanation why the following does give an error (see [here](http://stackoverflow.com/questions/27734211/handling-wrong-entries-and-nas-in-a-data-table-substituting-them-with-entries/27747859#27747859) ):
```R
for (j in  valCols)
   set(dt_,  
    i = which(is.na(dt_[[j]])),
    j = j, 
    value= as.numeric(originTable[[j]]))
```

**Comment by arunsrinivasan** [comment]
Added [Reshape vignette](https://rawgit.com/wiki/Rdatatable/data.table/vignettes/datatable-reshape.html) to [Wiki](https://github.com/Rdatatable/data.table/wiki/Getting-started).

**Comment by juancentro** [comment]
Excellent functionality and vignette! Thanks Arun

**Comment by jangorecki** [comment]
man for `patterns` would be good. Great vignette

**Comment by markdanese** [comment]
Isn't reshape2 required to be loaded to use these commands?  If so, then that should be mentioned.  I really like the focus on "wide to long" and "long to wide".  I absolutely hate the syntax of reshape2 (for example, I think "make_wide" is much more clear than "dcast").  For this reason, I would not write the section headers as "melting data.tables" and "casting data.tables".  That only make sense for people who are familiar with the reshape2 package.  I might begin with headers that are more universal as above ("long to wide").

For what it is worth, I can't get the first line of the vignette to run using a fresh R session with just data.table loaded.  I have no idea why (maybe mode should be "w" and not "wb"), but 
`DT = fread("https://raw.githubusercontent.com/wiki/Rdatatable/data.table/data/melt_default.csv")`
returns
`Error in download.file(input, tt, mode = "wb") : unsupported URL scheme`

As always, thanks for doing this.  It is really useful.

**Comment by arunsrinivasan** [comment]
@markdanese thanks for the excellent feedback.

1. `reshape2` won't be required from `data.table v1.9.6`. Updated this in the vignette as well.
2. Added 'wide to long' and 'long to wide' to titles, and other places to avoid confusion to people who are new to this topic.
3. `https` functionality in `fread` is implemented in the devel version. So you won't be able to run that code yet with `v1.9.4`. Either update, or wait a bit :-).

Thanks for your encouragement.

@jangorecki `patterns()` won't be exported. The usage will be expanded for `[.data.table` to be used for selecting columns, `:=`, `.SDcols` etc..

**Comment by jangorecki** [comment]
@arunsrinivasan still the manual for `patterns` may help, the same way there is one for `:=`. Just because many people (I think) use `?fun` to understand the code they read.

**Comment by jangorecki** [comment]
In the *join* vignette it may be worth to add corresponding SQL examples of data.table joins so it can be easier to pickup for db guys.

**Comment by MichaelChirico** [comment]
Would also be cool to have some "Refugees" vignettes --

 - `data.table` for `Stata` users
 - `data.table` for `SQL` users
 - `data.table` for `Matlab` users
 - `data.table` for `Python`/`pandas` users
 - even `data.table` for `dplyr` users

etc.

**Comment by arunsrinivasan** [comment]
Added `Secondary indices and auto indexing` vignette. This should allow smooth transition from subsets to joins for the next vignette I'll work on.

**Comment by jangorecki** [comment]
@arunsrinivasan isn't more appropriate to not use *secondary* in relation to *indices*? it was used for *keys* where it was important. Not seems to be redundant once we switch to *index* naming.

**Comment by MichaelChirico** [comment]
@jangorecki I think "secondary" is useful for its relation to keys (primary), perhaps:

Secondary sorting

Is a better description?

**Comment by jangorecki** [comment]
but already the *index* word has been used, it looks nicer than *secondary sorting* :)

**Comment by MichaelChirico** [comment]
So you would just name it "auto indexing"? IMO "secondary sorting and auto indexing" feels more informative

**Comment by jangorecki** [comment]
*auto* can be somehow misleading, as indexes should works for *auto* creating index, and also for use of manually created indexes - #1422 address current limitation in that matter.

**Comment by MichaelChirico** [comment]
I see. I'm still missing your preferred alternative -- just "Indices"?

**Comment by jangorecki** [comment]
not perfect but preferred over *secondary indices*

**Comment by markdanese** [comment]
I like this latest vignette a lot.  My only thought was that it might be helpful to mention what types of operations cause the index to be dropped.  From my testing, it seems pretty much anything that changes the number of rows, or any operation involving the indexed column.

I thought the examples of "on" were really helpful.

**Comment by arunsrinivasan** [comment]
@markdanese good point, will add.

**Comment by dracodoc** [comment]
I'm reading this vignette and like it! 

One minor issue I had is in 
`e) Compute or do in j`

`flights[, sum((arr_delay + dep_delay) < 0)]`

It took me some time to realize sum is applied to the resulting logical vector from the expression. I felt

`sum(flights[, (arr_delay + dep_delay) < 0], na.rm = TRUE)`

 will be easier to understand its intent, and separable with 

`flights[, sum(arr_delay)]`, which might be better suitable for this section.

**Comment by pakom** [comment]
Thank you for the updated vignettes with the release of v1.9.8.
The "Reference semantics" refers to the `copy()` function and its new capabilities to make shallow copies (especially inside functions something that I am really interested in):

"However we could improve this functionality further by shallow copying instead of deep copying. In fact, we would very much like to [provide this functionality for v1.9.8](https://github.com/Rdatatable/data.table/issues/617). We will touch up on this again in the data.table design vignette."

But the design vignette is missing and the link points to an old issue. The reference manual does not provide more information on `copy()` than the one provided in the vignette. The rest of the vignettes do not provide any information on `copy`.

Will this vignette become available soon?

**Comment by MichaelChirico** [comment]
+1 for internals vignette. I (and I guess a few others) am quite interested in contributing a bit on the C side of things, but am a bit intimidated by the (as it stands) 35k lines of C code... quite the learning curve to 'go it alone' -- an intro to internals could do wonders!

**Comment by MichaelChirico** [comment]
For Joins vignette:

https://github.com/Rdatatable/data.table/issues/2396

**Comment by zeomal** [comment]
Wanted to chime in and ask if contributions to the vignette are accepted from non-code contributors (like me). I am particularly interested in contributing to the joins vignette as I had quite a bit of trouble with it initially and was guided to solutions from Arun's answers on Stackoverflow, and I'd like some guidance on how to do so, if allowed.

**Comment by Henrik-P** [comment]
@arunsrinivasan I see that you have a point `IDateTime vignette`. Perhaps it could be included in the more general vignette suggested by @jangorecki: [vignettes: timeseries - ordered observations](https://github.com/Rdatatable/data.table/issues/3453)?

In addition, I am [preparing a first draft on some of the topics suggested by jan](https://github.com/Rdatatable/data.table/issues/3453#issuecomment-617717955). Perhaps parts of it may be relevant for a join vignette as well? I'm happy to share if anyone may find it useful.

**Comment by MichaelChirico** [comment]
@zeomal such a contribution would be highly valuable and much appreciated!

**Comment by zeomal** [comment]
@MichaelChirico, thank you. @Henrik-P , will your brief on normal joins be comprehensive - i.e. will your focus be more on timeseries? If not, I can start work on it.

**Comment by Henrik-P** [comment]
@zeomal Hopefully I will be able to upload the first draft soon, so you can have a look at it. In my draft, I provide a simple example of a "normal" join on a single variable, time, where there are non-matching rows. I use `nomatch = NA`. (maaaybe also a quick example with `nomatch = NULL`) 

My idea was that this simple join could provide a context and a feeling for the problem, which I then treat more thoroughly in the following sections on rolling and non-equi joins et al.

Thanks a lot for your willingness to contribute! .

**Comment by zeomal** [comment]
I have a question on joining by reference, while preparing the vignettes. The `X[Y, new_col := old_col]` performs something similar to a traditional left join on `X`. However, if there are multiple matches to `Y`'s keys in `X`, only the last (or first?) matching value of the key is retained. Is this explicitly documented somewhere? I had tried searching for this back when I encountered it, but had to resort to my understanding of updating by reference for the response. For a reproducible example, 

```
> X = data.table(a = c(1, 2, 3), m = c("a", "b", "c"))
> Y = data.table(b = c(1, 1, 4), n = c("x", "y", "z"))
> X[Y, new_col := i.n, on = "a == b"]
   a m new_col
1: 1 a       y
2: 2 b    <NA>
3: 3 c    <NA>
```
This is expected behaviour, but isn't exactly straightforward for a new user. `mult` does not impact the output either. How do you suggest I document this? Add `merge` as a workaround for a proper left join?

**Comment by jangorecki** [comment]
@zeomal could you please put your question in #2181 issue instead? just copy paste. It seems to better place.

**Comment by Henrik-P** [comment]
@zeomal I don't know if you get notifications, so I just want to let you know that I posted [a PR on a timeseries vignette](https://github.com/Rdatatable/data.table/pull/4400), if you wish to check how brief my treatment on normal (equi) joins is.

**Comment by kjytay** [comment]
Minor typo in `vignettes/datatable-reshape.Rmd` lines 113 and 129: `DT.m` should be replaced with `DT.m1`.

**Comment by MichaelChirico** [comment]
@kjytay could you please file a PR fixing that? you should be able to do so in the GitHub UI so it should be pretty quick

**Comment by MichaelChirico** [comment]
This issue is a bit too generic & dated; the main thing was the joins vignette which is done.

Closing, please file specific issues now.
